secret:
    create: ENC[AES256_GCM,data:cqz/BA==,iv:ghYuN9nNLO2vR8YYDCY7dbocnRTPCMeCLh+1JglDv5w=,tag:WSF8JhkSFItIAMo7upo5sw==,type:bool]
    name: ""
    mountPath: ENC[AES256_GCM,data:L3xLuNtuPh4/vpoAA200uX4=,iv:+RrbKNRRWlNDbALYwBjdCmRtz2CJftdd2YFUr4sq/54=,tag:NSnCLfZWlEuTl00tJcRAlA==,type:str]
    data:
        piped-key: ENC[AES256_GCM,data:y1YnOaOLAZlzbhr4B4q6rbi7Y/CGPOm2Y394Lgi5WXWkkR0IasRC9UB4U3iE3Oyky0A=,iv:7VcYxG4lA2hU9a19ju/jXubGAYuDUaTGnivoEJsxlHY=,tag:5KzWBh13jij0ItlWIXivSQ==,type:str]
        ssh-key: ENC[AES256_GCM,data:frzaee1D9vfBfjuLC4VjX7mSETfAc3JZURrsw/Uo8H3jAmIsQAaWE+FPfkC2l6pQgBS2kjT8HUdRX+KFd0lVpArHDC9DQwlF9PWLCUOoIkq23rZZ3emf/1WYiF/u7nkPBZ8tHGKiqxKxceifv5bZX+DmPW7J0Vpwg947tarGMu9qnNfxbBR8bcvCO9rCBfxInhJlN4DqDtavzkHLNqNqobXFq6JjMn5fiwA2eTKv7Yr/lxG4zbHrOVZBOO2ci/x7yEWSC5tQeScsBWnM2vqbk9mKrlyZ9x2e+0Wd+c1UDxFYKGfccomBncsSB99/Xsh34/Bli5/EQj0k5hzrCg/XOufK2x0SqoulR43RrISMhr0m4sdOVS0ERw12cbmqBdaab8kLvyesswjbIyAdx/KrvBm/tzgOIlkEKw1gP3FNQlmCohQ6tndXP79nkHNri7UtCokj7SSyJLnSOwtcsNDMJpidXs+yGi6w2s2L+Ya0ZS9hGXyw6h4D4k91Ga1bs4OtjXToIypCy/hxaUrg6BOsHaRuro8Tl+LBGpJr,iv:3O5p1U46k9G98iBtxp+zb5KC7v4y6Eb+jW2aF4Xx2zs=,tag:bVrvmVJuwRkCeubzePslhQ==,type:str]
    kubeConfigs: []
args:
    insecure: ENC[AES256_GCM,data:igVmXw==,iv:6bNrGnhIOrRSOOISKwZ4hiDiyG6Z456Ab4gh9AQ0Oig=,tag:0jxcii6VqH5e2BzlTtpj0Q==,type:bool]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/sreake-intern/locations/asia-northeast1/keyRings/storage-bucket-keyring-asia/cryptoKeys/storage-bucket-crypto-key-asia
          created_at: "2023-11-30T01:28:42Z"
          enc: CiUAJ8ihWiyLI6DuJThKcDLFZlv8NQrZ2zBPADQmQzV9N70lOWYTEkkAuWn4PWX4JvK8IiCxxtTSn9IGzJo5Yaf83O168tcSxQzzLkcmtPQ5iqP/BiupNR8mIrLU+7HR+VHmfjKSZ6+Ff3f0ysxXtq8m
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-11-30T01:28:43Z"
    mac: ENC[AES256_GCM,data:cIMx5xyjEnyAhV9Ua2P5Prxqh7k6QG0wC144IzOiG9hDyUfwBgtLDF6qSEcNZJ6hbR9FoTeMos6TCWtFKqeV/cvzonlD8xsydjmW42+3SK38ihy9X58Olsq+/P0US2CsvgHMlHWQMYT3NjTn7mxEPepj7dObLWKTEJh3L+Zx7xw=,iv:qg9BTqAQ0UIXymrYoI1xlm4OqxhnuRxGuH3mrfZIYhQ=,tag:QmvYA7nc0q2C9mADA/FbOA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
