secret:
    create: true
    name: ""
    mountPath: /etc/piped-secret
    data:
        piped-key: 6slnrne47ow6v6e6sxw0ta3i07696k7jvlew1u6los92e1mxv6
        ssh-key: |
          -----BEGIN OPENSSH PRIVATE KEY-----
          b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
          QyNTUxOQAAACDxA1Iu/4J2iKbQEG/2A+CjHLGLjG6Nu0P2pyz47JeSmAAAAJi59BFaufQR
          WgAAAAtzc2gtZWQyNTUxOQAAACDxA1Iu/4J2iKbQEG/2A+CjHLGLjG6Nu0P2pyz47JeSmA
          AAAEB0e1qfustnQC2/xtsBX66gwNGMaTOd3rHEJfUu5HyAXfEDUi7/gnaIptAQb/YD4KMc
          sYuMbo27Q/anLPjsl5KYAAAAE3BpcGVjZC1zc2gtMjAyMzExMTMBAg==
          -----END OPENSSH PRIVATE KEY-----
    kubeConfigs: []
args:
    insecure: true