config:
  data: |
    apiVersion: pipecd.dev/v1beta1
    kind: ControlPlane
    spec:
        datastore:
            type: MYSQL
            config:
                url: root:test@tcp(pipecd-mysql:3306)
                database: pipecd-database
        filestore:
            type: MINIO
            config:
                endpoint: http://pipecd-minio:9000
                bucket: quickstart
                accessKeyFile: /etc/pipecd-secret/minio-access-key
                secretKeyFile: /etc/pipecd-secret/minio-secret-key
                autoCreateBucket: true

mysql:
    database: pipecd-database
    image: mysql
    rootPassword: test
secret:
    encryptionKey:
        data: encryption-key-just-used-for-quickstart
    minioAccessKey:
        data: quickstart-access-key
    minioSecretKey:
        data: quickstart-secret-key
    internalTLSCert:
        data: |
            -----BEGIN CERTIFICATE-----
            MIIDITCCAgmgAwIBAgIUHL0q2yklx5vGZ5c0wOLPYB0Y2kQwDQYJKoZIhvcNAQEL
            BQAwIDEeMBwGA1UEAwwVcGlwZWNkLmdhd2luZ293aW4uY29tMB4XDTIzMTEyMTA3
            MzkwM1oXDTMzMTExODA3MzkwM1owIDEeMBwGA1UEAwwVcGlwZWNkLmdhd2luZ293
            aW4uY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAj/TO+IZC+S3m
            Hoozx5Xu6p5QRjSjGTNEH81IQV3fzdeKPYYBjZM6IEdhTvHSunoNetTUojl4tO7S
            pfbrCO33ZZWVBSK7ab+ie9nQWZ6W27v1sOhWmijCR1S99N0rTlD+rTv+zRl/VLdj
            9QLILi1hfLwvN+etfnp+SW2+Wzmr505JBuFByIwLp+WCIGST7s1U8crUeNcYAw+A
            gChNViq3PUfE2xezEfa2kMjj5CzyyzD+NJsDC7jdHH2te1unC51XJrkaLwz6HSWb
            OjKYw3ZNX1pKLBLVG/24ZDGaKhZtD6KFm18Tagbn1giDECwaP1t2G2C0Pa9VP5Hf
            Rc9uDFjKfwIDAQABo1MwUTAdBgNVHQ4EFgQUDnKPxeQpitIjyyJWHlieDjBVYjsw
            HwYDVR0jBBgwFoAUDnKPxeQpitIjyyJWHlieDjBVYjswDwYDVR0TAQH/BAUwAwEB
            /zANBgkqhkiG9w0BAQsFAAOCAQEAQpoMU0Rt/covH1e4Nn0FsFwiA7pGR/P5qcuL
            3/sw5GgyNFMyf8sg/8gwI7b818YWJmTjg8BMXD0ZgDdtbOBu1lbWgjyymnHVNiHl
            lAfNGT3kiOmjbiRzays4MOSO1wdYOF0QZoVkKOMA5xKs9UKGQ3WKtKbx7wjx/bU+
            ypGcqflJq8zpRFFPN2PDTyb75323NeUyc0zLJ+qhH4r/qnSjbT0z9a6uIGyS+dm8
            2up6+rl9Ih0JPpqbu9AIQUmnm0Gk/RtyXp420wJhJIRShB5e4Iud8tyUPL/T+VWF
            qZu+ixiMQ9QhaQLP303FX6iukyg7gh1e2nL7fRXB1JAqwn5zJA==
            -----END CERTIFICATE-----
    internalTLSKey:
        data: |-
            -----BEGIN PRIVATE KEY-----
            MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCP9M74hkL5LeYe
            ijPHle7qnlBGNKMZM0QfzUhBXd/N14o9hgGNkzogR2FO8dK6eg161NSiOXi07tKl
            9usI7fdllZUFIrtpv6J72dBZnpbbu/Ww6FaaKMJHVL303StOUP6tO/7NGX9Ut2P1
            AsguLWF8vC83561+en5Jbb5bOavnTkkG4UHIjAun5YIgZJPuzVTxytR41xgDD4CA
            KE1WKrc9R8TbF7MR9raQyOPkLPLLMP40mwMLuN0cfa17W6cLnVcmuRovDPodJZs6
            MpjDdk1fWkosEtUb/bhkMZoqFm0PooWbXxNqBufWCIMQLBo/W3YbYLQ9r1U/kd9F
            z24MWMp/AgMBAAECggEAHdewOFEM/T8In3gi99MbLkQXfBZZYVYBX15dBkABr1hp
            bgujsse8mwhxIb574vB+buJEGkUzwr5nqMQhQT6jtMlnlSL4GxoBAw/KY2m++Fpk
            uoHPwjGE5OiqYGKhIaEkyqDPV5FbliJWdGpZOUlrFkKkv0Al9TxLhclcVukDu/Vt
            ER5Ch+OTHChsm6N99b9Dl+/fFepVPRtLp2N+6M95YCouHAA6e0fbzH6h1qNFVmlp
            1YZwv3yBlBtu/8Tn8vHcTN3GD01rWItZTZnxaNzFK6SS1V1HxSJF6RSfYSc87Fpx
            dobUJOq7SpwNhKRq9b7g44hs3BuqaXvujc3Cf1TVcQKBgQC9+pYjopGl9369AFZR
            i9JffGgZ8KMGfkHux19u4xQBCAj1pJS6iVXH3kiVMilVITA+5hsRvsRJvvl8E/ia
            M67xJcV/YSTp2jLosn7u0YEwwGzAv9FUwQMn1i5e3BAn8ifoIcCqGs0yg8vhUf5w
            kTNZxv0CGEWNCaoi0yaL760/GwKBgQDB+9ZfpMBXmX9KAR0deAYNBvnnrwfg/Wzk
            A8um7rqQ+y4It9fUjY8f1T1Lsbq7XdNeb7IijrGM1YbZC6lNSgKJc9ERJ8JnNBYz
            SOTJgr49lpECUfyXHB4yIEyPRekP32wcCyfzvAIK18UqTaZNf2Q+zfBx9QPBtPm2
            KMod0tGEbQKBgGtI4hTJr9q8A7SURirS/UCzLs7HWClIj89ahAhI8HkMopKmGN+m
            wuyWGQM4SqMqlOZQaCUDSDIlSRrK5G+glEDWhcvDfmcZs/o5IvmXEpAHeuL28C4e
            ubt7dsBXIkCMvgCXXwgxDoRibXaXKUtElG00tJjEQDK/rHbyKyiHd5zVAoGBAJ5H
            QDm2EgLoCgZ2Ni1vW3CRuqMiG8mmvoyl1CuXKr9VU9BlQUP7ZUbSFTuH/xcWjXrG
            pJCx4YlKSMccTr3zn3JL/9CBoovW4i5iUdtiRJu4GQXNo84gcTrxQ8a7glkjMfEH
            4UdspjX2rLfBt+oQAdmE66XwB2qsofvR+GixNadZAoGBAJv0T79uler+rVJSc8vN
            prNcbqP/VJGfy7XQ+dAhSmiPiUQkI9yKewziGQjoExZrG/3Rf0paLvw8PQ2JbrsI
            ueN1eAqjasaoPj5D9HIUoGC5fPg05fum1YlGt/md39tDw1pOlaCmyC/vcrGXQrMw
            o8nmdd1qecwpVhZjRX98+dpR
            -----END PRIVATE KEY-----